name: widgetkit
description:
  A kit of widgets that are (almost) always needed in the different apps.
version: 1.0.1
homepage: https://github.com/CodingAleCR/widgetkit

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
