name: widgetkit
description:
  A kit of widgets that are (almost) always needed in the different apps.
version: 0.4.0
homepage: https://github.com/CodingAleCR/widgetkit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
